# 넘파이 (Numpy)
- ndim : 축의개수
- shape : 배열의 차원정보
- size : 배열안에 있는 원소의 총 개수
- dtype : 배열 원소의 자료형 

### 1차원과 속성들

In [17]:
# list = [11,22,33,44,55]
import numpy as np
narr = np.array(range(7))
print(narr)
print(type(narr))
print(narr.ndim)
print(narr.shape)
print(narr.size)
print(narr.dtype)
print(narr[3])
print(narr[2:5])

[0 1 2 3 4 5 6]
<class 'numpy.ndarray'>
1
(7,)
7
int64
3
[2 3 4]


In [18]:
narr1 = np.array([1,2,3,4]) # int64
narr2 = np.array([1,2,'apple','banana'])
narr3 = np.array([1,2,3,4], dtype='str')
print(narr1, narr1.dtype)
print(narr2, narr2.dtype)
print(narr3, narr3.dtype)

[1 2 3 4] int64
['1' '2' 'apple' 'banana'] <U21
['1' '2' '3' '4'] <U1


In [38]:
narr4 = np.zeros(10, dtype='int64')
narr5 = np.ones(10, dtype='int64')
narr6 = np.full(5,2, dtype='float64')
narr7 = np.full(5,'ok')
narr8 = np.linspace(0,10,5, endpoint=False)
narr9 = np.arange(10)
print(narr4, narr4.dtype)
print(narr5, narr5.dtype)
print(narr6, narr6.dtype)
print(narr7, narr7.dtype)
print(narr8, narr8.dtype)
print(narr9, narr9.dtype)

[0 0 0 0 0 0 0 0 0 0] int64
[1 1 1 1 1 1 1 1 1 1] int64
[2. 2. 2. 2. 2.] float64
['ok' 'ok' 'ok' 'ok' 'ok'] <U2
[0. 2. 4. 6. 8.] float64
[0 1 2 3 4 5 6 7 8 9] int64


In [50]:
# 2차원
arr1 = np.zeros((2,2))
arr2 = np.ones((2,2))
arr3 = np.full((2,2),5)
arr4 = np.eye(2)
print(arr1,arr1.dtype)
print(arr2,arr2.dtype)
print(arr3,arr3.dtype)
print(arr4,arr4.dtype)

[[0. 0.]
 [0. 0.]] float64
[[1. 1.]
 [1. 1.]] float64
[[5 5]
 [5 5]] int64
[[1. 0.]
 [0. 1.]] float64


In [52]:
# 2차원 배열
nar = np.array([[1,2],[3,4]])
print(nar, nar.ndim, nar.dtype, nar.shape, nar.size, type(nar))

[[1 2]
 [3 4]] 2 int64 (2, 2) 4 <class 'numpy.ndarray'>


In [63]:
# 2차원 타입변환
nar1 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
nar2 = np.arange(1,10).reshape(3,3)
nar3 = np.arange(1,11).reshape(2,5)
nar4 = np.arange(1,11).reshape(5,2)
nar5 = np.arange(1,28).reshape(3,3,3)
print(nar1, nar1.ndim,nar1.dtype, nar1.shape, nar1.size, type(nar1) )
print(nar2, nar2.ndim,nar2.dtype, nar2.shape, nar2.size, type(nar2) )
print(nar3, nar3.ndim,nar3.dtype, nar3.shape, nar3.size, type(nar3) )
print(nar4, nar4.ndim,nar4.dtype, nar4.shape, nar4.size, type(nar4) )
print(nar5, nar5.ndim,nar5.dtype, nar5.shape, nar5.size, type(nar5) )

[[1 2 3]
 [4 5 6]
 [7 8 9]] 2 int64 (3, 3) 9 <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]] 2 int64 (3, 3) 9 <class 'numpy.ndarray'>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 2 int64 (2, 5) 10 <class 'numpy.ndarray'>
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] 2 int64 (5, 2) 10 <class 'numpy.ndarray'>
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]] 3 int64 (3, 3, 3) 27 <class 'numpy.ndarray'>


In [75]:
t1 = np.arange(1,22).reshape(3,7)
t2 = np.arange(1,8).reshape(7,1)
t3 = np.arange(1,11).reshape(5,2)
t4 = np.arange(1,13).reshape(4,3,1)
print(t1)
print("="*23)
print(t2)
print("="*23)
print(t3)
print("="*23)
print(t4)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [108]:
print(t1[1][2:5])
print(t1[1:3, 2:5])
# 브로드캐스팅
print(t1 * 10)
print(t1 % 2 == 0)
print(t1[t1 % 2 == 0])

[10 11 12]
[[10 11 12]
 [17 18 19]]
[[ 10  20  30  40  50  60  70]
 [ 80  90 100 110 120 130 140]
 [150 160 170 180 190 200 210]]
[[False  True False  True False  True False]
 [ True False  True False  True False  True]
 [False  True False  True False  True False]]
[ 2  4  6  8 10 12 14 16 18 20]


In [105]:
l1 = [6,7,8,9,10]
l2 = [1,2,3,4,5]
print(l1 + l2)
np1 = np.array(l1)
np2 = np.array(l2)
np3 = np1 + np2
print(np3.tolist())
print("덧셈:",np1 + np2)
print("뺄셈:",np1 - np2)
print("곱셈:",np1 * np2)
print("나눗셈:",np1 / np2)

[6, 7, 8, 9, 10, 1, 2, 3, 4, 5]
[7, 9, 11, 13, 15]
덧셈: [ 7  9 11 13 15]
뺄셈: [5 5 5 5 5]
곱셈: [ 6 14 24 36 50]
나눗셈: [6.         3.5        2.66666667 2.25       2.        ]


In [112]:
# flatten 처리
ff = np.arange(1,10).reshape(3,3)
print(ff)
print(ff.reshape(9))
print(ff.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


### Random number 발생
- np.random.randint(): 균일 분포의 정수 난수
- np.random.rand(): 0부터 1사이의 균일 분포 난수 생성
- np.random.randn(): 표준 정규 분포 난수 생성
- np.random.normal(): 정규 분포 난수 생성

In [113]:
# randomint()
# RGB (세로픽셀수, 가로픽셀, 색상체널)
x = np.random.randint(0,255,size=(3,3,3))
x

array([[[102, 149,  67],
        [ 82,  68,  26],
        [178, 108,  69]],

       [[ 51,  20, 231],
        [185,  95, 134],
        [211, 120, 147]],

       [[139, 157,  75],
        [103, 201,  22],
        [ 21,  59,  20]]])

In [118]:
print('평균값:',np.mean(x),',표준편차:',np.std(x),',최소값:',x.min(),',최대값:',x.max())

평균값: 105.18518518518519 ,표준편차: 61.46666488131899 ,최소값: 20 ,최대값: 231


In [120]:
x2 = np.random.normal(5,3,(10,5)) # 평균이 5, 표준편차가 3
x2

array([[ 6.72944197,  2.22991964,  9.65441115,  7.36611256,  0.57812374],
       [ 0.84558222,  2.61200445,  5.90798778,  1.30644573,  5.58424924],
       [-2.3654067 ,  4.99201629,  0.89635482,  2.16069039,  3.09275991],
       [ 0.99129909,  3.98023966,  4.84656952,  7.14381321,  5.78551476],
       [ 3.7229684 ,  5.70214073, 11.76101694,  5.50050697,  2.70714333],
       [ 4.44440092, -0.33226983,  8.88124399,  5.71664829,  3.53531144],
       [ 6.35962643,  9.52161467,  3.47340464,  6.54839931,  6.36993661],
       [10.65258787,  4.67236313,  5.87295434,  0.37204787,  9.20623615],
       [ 1.1093916 ,  8.17161422,  2.3469969 ,  3.83412558,  5.43916838],
       [ 4.39181742,  4.28040702,  0.34572317,  6.01318397,  4.16688861]])

In [122]:
x3 = np.random.randn(10,5) # 표준 정규 분포 난수 생성
x3

array([[-1.12027571, -0.21043118,  0.66623838,  0.07599111, -0.40698257],
       [ 0.39614849,  1.79084768, -0.61854967,  0.59898718, -0.06151723],
       [-0.93776505, -1.87283825, -0.76566012, -0.08471815, -0.36933061],
       [ 0.17225495, -0.27052759,  1.03560141, -0.8989627 ,  0.85584732],
       [ 1.40463562, -0.39610111,  1.35558499, -1.55351749,  0.706467  ],
       [ 1.43990617, -0.41161855, -1.07461786,  0.08323853,  0.98391956],
       [ 1.72912499, -0.18847945,  0.43826206, -1.08867449,  1.76463101],
       [ 1.92828013,  1.68811347, -1.21873063,  0.03775817,  1.45153894],
       [ 1.27267318,  0.29294698, -0.13738518, -1.26685673, -1.82698904],
       [-0.38060577, -0.72583723, -0.56409064,  2.84888365,  1.1813564 ]])

In [126]:
x4 = np.array([3,1,2,3,5,0,4,5,0,44,5,0,6,0,56,0,5,60,0,5,6])
print(len(x4))
print(np.count_nonzero(x4))
print(len(x4)-np.count_nonzero(x4))

21
15
6


In [134]:
print(np.mean(x2)) # 평균
print(x2.mean())
print(np.var(x2)) # 분산
print(x2.var()) 
print(np.std(x2)) # 표준편차
print(x2.std())
print(x2.min()) # 최소값
print(x2.max()) # 최대값
print(np.median(x2)) # 중간값

4.5825145697454746
4.5825145697454746
9.007271963621692
9.007271963621692
3.0012117492142556
3.0012117492142556
-2.3654067035212796
11.761016941024334
4.55838202547184


In [136]:
print(np.percentile(x2,0)) # 최소값
print(np.percentile(x2,25)) # 하위 25% , 제 1사분위수
print(np.percentile(x2,50)) # 중앙값 , 제 2사분위수
print(np.percentile(x2,75)) # 상위 25% , 제 3사분위수
print(np.percentile(x2,100)) # 최대값

-2.3654067035212796
2.4132487851548965
4.55838202547184
6.2730158129392395
11.761016941024334
